### ISSUE TITLE
securecookie: the value is not valid

### ISSUE THREAD

**Issue by superboum** [superboum/moolinet#5]
If you change Moolinet cookie key, the app fails to load and the server ouput `securecookie: the value is not valid`.

Should we catch this error and remove the cookie to prevent future problems ?

**Comment by johnbalvin** [comment]
That error is normal if you change the cookie key
This package imports gorilla sessions see https://github.com/heptiolabs/gangway/issues/16

**Comment by superboum** [comment]
Thanks for the information!

The cookie is already statically set: https://github.com/superboum/moolinet/blob/ce44239dc98c3dae6e5759254d4ae0926c9b027f/lib/web/auth_middleware.go#L27-L30

The information is taken from the json config file:
https://github.com/superboum/moolinet/blob/56af0329d187c431227ea16ccbada9c54635c2db/moolinet.json#L5

Maybe we should add a warning in the README in case users first run the program without modifying the config file and the secret key, and re-run it again after having configured it and face this error. For now, I think I will just close this issue :)
